name: Install dependencies
description: Configures the JSR npm registry and installs npm dependencies.

runs:
  using: composite
  steps:
    - name: Install dependencies
      shell: bash
      run: |
        npm config set @jsr:registry https://npm.jsr.io --location=project
        npm install
