version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    target-branch: "main"
    groups:
      astro:
        patterns:
          - "astro"
          - "@astrojs/*"
          - "@deno/astro-adapter"
          - "astro-icon"
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react*"
      tailwind:
        patterns:
          - "tailwindcss"
          - "@tailwindcss/*"
          - "@iconify/*"
          - "@catppuccin/*"
          - "daisyui"
      individual_task_display:
        patterns:
          - "@lyfie/*"
      clerk:
        patterns:
          - "@clerk/*"
      misc_core:
        patterns:
          - "@anthropic-ai/*"
          - "typescript"
          - "@google/genai"
          - "fractional-indexing"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    target-branch: "main"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    target-branch: "main"
