services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
      args:
        - LOCAL_MACHINE_GID=${LOCAL_MACHINE_GID}
    command: tail -f /dev/null
    tty: true
    cap_drop:
      - ALL
    cap_add:
      # required for init-firewall.sh. 
      # this stops Claude from being able to access the entire web
      - NET_ADMIN
      - NET_RAW 
      # required for basic webserver capabilities
      - NET_BIND_SERVICE
      - CHOWN
      - SETUID
      - SETGID
    env_file:
      - .env
    volumes:
      - .:/var/dev
    ports:
      - "4321:4321"
