services:
  app:
    build:
      context: .
      dockerfile: images/app.Dockerfile
      target: dev
      args:
        - LOCAL_MACHINE_GID=${LOCAL_MACHINE_GID}
    command: tail -f /dev/null
    tty: true
    cap_drop:
      - ALL
    cap_add:
      # required for init-firewall.sh. 
      # this stops Claude from being able to access the entire web
      - NET_ADMIN
      - NET_RAW 
      # required for basic webserver capabilities
      - NET_BIND_SERVICE
      - CHOWN
      - SETUID
      - SETGID
    labels:
      # THIS REPO REQUIRES THIS TO ALSO BE RUNNING: https://github.com/kimdcottrell/localdev-proxy
      - traefik.enable=true
      - traefik.http.middlewares.kanary-redirect-web-secure.redirectscheme.scheme=https
      - traefik.http.routers.kanary.middlewares=kanary-redirect-web-secure
      - traefik.http.routers.kanary-web.rule=Host(`kanary.local.dev`)
      - traefik.http.routers.kanary-web.entrypoints=web
      - traefik.http.routers.kanary-web-secure.rule=Host(`kanary.local.dev`)
      - traefik.http.routers.kanary-web-secure.tls=true
      - traefik.http.routers.kanary-web-secure.entrypoints=web-secure
      - traefik.http.services.kanary-web-secure.loadbalancer.server.port=4321
    extra_hosts:
      - host.docker.internal:host-gateway # used in deno task webhook
    env_file:
      - .env
    volumes:
      - .:/var/dev
      - ${HOME}/.ssh/agent.sock:/ssh-agent # TODO: this should be a mount in devcontainer.json, but the devcontainer setup process ignores mounts except on vscode window reload
    networks:
      - mcp 
      - proxy

  playwright:
    build:
      context: .
      dockerfile: images/playwright.Dockerfile
    stdin_open: true
    tty: true
    init: true
    volumes:
      - .:/var/dev
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - "3000:3000"
    networks:
      - proxy

  mcp_playwright:
    image: mcr.microsoft.com/playwright/mcp
    stdin_open: true
    init: true
    ports:
      - "8931:8931"
    command: --port 8931 --host 0.0.0.0 --allowed-origins '*' --allowed-hosts '*'
    networks:
      - mcp

  mcp_mcpdoc:
    build:
      context: .
      dockerfile: images/mcpdoc.Dockerfile
    ports:
      - "8082:8082"
    volumes:
      - .mcpdoc.yaml:/root/.local/mcpdoc.yaml
    command: uvx --from mcpdoc mcpdoc --yaml /root/.local/mcpdoc.yaml --transport sse --port 8082 --host 0.0.0.0 --allowed-domains '*'
    networks:
      - mcp

networks:
  mcp:
  proxy:
    external: true
