name: Generate Lighthouse Report

on:
  pull_request:
  workflow_run:
    workflows: [Unit Tests]
    types:
      - completed

jobs:
  lighthouseci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Wait for Deno Deploy and get preview URL
        id: preview-url
        uses: ./.github/actions/deno-deploy-preview-url
        with:
          deno-deploy-token: ${{ secrets.DENO_DEPLOY_TOKEN }}
          gh-token: ${{ github.token }}
          sha: ${{ github.event.pull_request.head.sha }}
          repository: ${{ github.repository }}

      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v12
        with:
          urls: |
            ${{ steps.preview-url.outputs.base_url }}
          uploadArtifacts: true # save results as an action artifacts
          temporaryPublicStorage: true # upload lighthouse report to the temporary storage